### PR TITLE
Update server.js

### PR DESCRIPTION
**Pull request by davidkhala**
Some comments:
1. why there is hybrid usage of const and var
2. express.js is not required for this task
That is why I suspected this task was not solely implemented by your own.

### CODE REVIEW

**Comment by oussema** [comment]
1. Thanks Sir for this advice, I'll pay attention in the future of the type of the variables that I choose.
2.Do you mean that I shouldn't use express.js in my project ?

**Comment by davidkhala** [comment]
2. then please explain why you use express.js for this crypto library task?

**Comment by davidkhala** [comment]
consistent, tidy code, format beautified is the least requirement for any code projects. We could not be satisfied with simply 'working project'.

**Comment by oussema** [comment]
2-I thought that I need to run it as a server to compile the javascript file.
But I was wrong.

**Pull request merged**
